# Lecture 3

- Statistics Recap
- Correlation Coefficients
- Linear Modelling

## Statistics Recap

### Expectation and Variance

![image](../attachments/seeingTheory.png)

[Seeing Theory by Brown University](https://seeing-theory.brown.edu/)

### Correlation Coefficients

Roughly: measuring interdependence of two variables.

Pearson's R Correlation Coefficient:
- Ranges from $1$ (positively correlated) to $-1$ (negatively correlated)

$$ r = \frac{\sum_i (x_i - \bar{x})(y_i - \bar{y})}
                    {\sqrt{(\sum_i (x_i - \bar{x})^2)(\sum_i (y_i - \bar{y})^2)}}
                    = \frac{cov(x,y)}{\sigma_x \sigma_y} $$

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

df[['total_bill', 'tip', 'size']].corr(numeric_only=True)

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

This table is called the correlation matrix, the closer it is to 1, the more strongly variable x and y are related.

Correlation does not imply causation!!!

In [ ]:
import numpy as np

n = 365 
temperature = np.random.normal(75, 10, n)

# generate dummy data

ice_cream_sales = 200 + 3 * temperature + np.random.normal(0, 20, n)
crime_rate = 50 + 2 * temperature + np.random.normal(0, 15, n)

df = pd.DataFrame({
    "temperature": temperature,
    "ice_cream_sales": ice_cream_sales,
    "crime_rate": crime_rate
})

df[['ice_cream_sales', 'crime_rate']].corr()

                 ice_cream_sales  crime_rate
ice_cream_sales          1.00000     0.60959
crime_rate               0.60959     1.00000

Claim: Higher ice cream sales cause more crime.

Reality:
- Temperature is a **confounding** variable
- Hot days -> more ice cream sales
- Hot days -> more people outside -> more crime

![image](https://www.simplypsychology.org/wp-content/uploads/correlation-coefficient.jpg)

[Lies, damned lies, and statistics](https://en.wikipedia.org/wiki/Lies,_damned_lies,_and_statistics)

![image](../attachments/ubc_guess_correlation.png)

[Let's try to guess the correlation](https://shiney.zoology.ubc.ca/whitlock/Guessing_correlation/)

### Summary Statistics

![Normal](../attachments/ds8_normal_curve_ch14.png)

$$\phi(z) = \frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}z^2}, -\infty < z < \infty$$

- The curve is symmetric about 0 with its mean and median both 0.
- Pandas:  x.mean() and x.median()
- If a variable has this distribution, its SD is 1.
- Pandas:  x.std()

## Linear Modeling

We can score each line with how close the actual and predicted y-values are, using RMSE for the loss function.

The line with the best score is determined as the regression line.

We can visualize this process [here](https://setosa.io/ev/ordinary-least-squares-regression/)

Our goal in linear regression is to seek the line $y=mx+b$ that minimizes the least square errors

That is to say, the line that minimizes the mean of the MSE(mean squared errors) for all lines.

When x and y are in standard units, regression line is:

$$ y = r*x + 0$$

Let's try a [game](https://regression.historyofdatascience.com/)!